FROM trufflesuite/ganache-cli:v6.7.0

COPY ./data /blockchain

ENTRYPOINT [ \
    "node", "/app/ganache-core.docker.cli.js", \
    "--accounts", "20", "--defaultBalanceEther", "10000", \
    "--mnemonic", "myth like bonus scare over problem client lizard pioneer submit female collect", \
    "--gasLimit", "0xfffffffffff", "--gasPrice", "1", \
    "--port", "1545", "--networkId", "5777", \
    "--db", "/blockchain" \
]
